server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_user_service?useSSL=false&serverTimezone=UTC
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: YOUR_GOOGLE_CLIENT_ID
#            client-secret: YOUR_GOOGLE_CLIENT_SECRET
#            scope: openid, profile, email
#            redirect-uri: "{baseUrl}/oauth2/callback/google"
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#          facebook:
#            client-id: YOUR_FACEBOOK_CLIENT_ID
#            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
#            scope: email, public_profile
#            redirect-uri: "{baseUrl}/oauth2/callback/facebook"
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#        provider:
#          facebook:
#            authorization-uri: https://www.facebook.com/v15.0/dialog/oauth
#            token-uri: https://graph.facebook.com/v15.0/oauth/access_token
#            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
#            user-name-attribute: id
#
#jwt:
#  secret: your_super_secret_key_256bit
#  expiration: 900
#  refresh-expiration: 2592000
